curl -X 'POST' \
  'http://localhost:8000/inference' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "request_id": "1",
  "model_name": "14e",
  "img_dir": "dataset/example/test1.jpg"
}'